describe('template spec', () => {
  beforeEach(() => {
    cy.visit('https://demowebshop.tricentis.com/register')
  })
  it('Failed Register - Password cant Empty', () => {
    cy.get('#gender-male').click()
    cy.get('#FirstName').type('JOHN')
    cy.get('#LastName').type('WICK')
    cy.get('#Email').type('john@go.com')
    cy.get('#Password')
    cy.get('#ConfirmPassword')
    cy.get('#register-button').click()
    cy.get(':nth-child(1) > .field-validation-error > span').should('contain.text','Password is required')
  })  
  it('Failed Register - Invalid Email', () => {
    cy.get('#gender-male').click()
    cy.get('#FirstName').type('JOHN')
    cy.get('#LastName').type('WICK')
    cy.get('#Email').type('john.com')
    cy.get('#Password').type('jhonyespapa')
    cy.get('#ConfirmPassword').type('jhonyespapa')
    cy.get('#register-button').click()
    cy.get('.field-validation-error > span').should('contain.text','Wrong email')
  })
  it('Failed Register - Email already exist', () => {
    cy.get('#gender-male').click()
    cy.get('#FirstName').type('JOHN')
    cy.get('#LastName').type('WICK')
    cy.get('#Email').type('john.wick@g.com')
    cy.get('#Password').type('jhonyespapa')
    cy.get('#ConfirmPassword').type('jhonyespapa')
    cy.get('#register-button').click()
    cy.get('.validation-summary-errors > ul > li').should('contain.text','The specified email already exists')
  })
  it('Success Register - Valid Data Input', () => {
    cy.get('#gender-male').click()
    cy.get('#FirstName').type('JOHN')
    cy.get('#LastName').type('WICK')
    cy.get('#Email').type('john.wick@go.com')
    cy.get('#Password').type('jhonyespapa')
    cy.get('#ConfirmPassword').type('jhonyespapa')
    cy.get('#register-button').click()
    cy.get('.result').should('contain.text','Your registration completed')
    cy.get('.page-body > .buttons > .button-1').click()
    cy.get('.topic-html-content-body > :nth-child(1)').should('contain.text','Welcome to the new Tricentis store!')
  })
  
  // it('Failed Login - Invalid Password', () => {
  //   cy.get('.panel > .header > .authorization-link > a').click()
  //   cy.get('.login-container > .block-customer-login > .block-title > #block-customer-login-heading').should('be.visible')
  //   cy.get('#email').type('wahidazi1st@gmail.com')
  //   cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('salah')
  //   cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
  //   cy.get('.message-error > div').should('be.visible')
  // })
  // it('Failed Login - Invalid Email', () => {
  //   cy.get('.panel > .header > .authorization-link > a').click()
  //   cy.get('.login-container > .block-customer-login > .block-title > #block-customer-login-heading').should('be.visible')
  //   cy.get('#email').type('*')
  //   cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .password > .control > #pass').type('Wa123456')
  //   cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
  //   cy.get('#email-error').should('contain.text','Please enter a valid email address')
  // })
  // it.only('Success Reset Password - Pass forgot password', () => {
  //   cy.get('.panel > .header > .authorization-link > a').click()
  //   cy.get('.login-container > .block-customer-login > .block-title > #block-customer-login-heading').should('be.visible')
  //   cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > .secondary > .action > span').click()
  //   cy.get('.note').should('be.visible')
  //   cy.get('#email_address').type('wahidazis1st@gmail.com')
  //   cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
  //   cy.get('.message-success > div').should('be.visible')
  // })
})